import type { Metadata } from "next";
import { Gilda_Display, Barlow, Barlow_Condensed } from "next/font/google";

import { Footer } from "@/components/footer";
import { Header } from "@/components/header";

import { RoomProvider } from "@/context/room-context";

import "./globals.css";

const gildaDisplay = Gilda_Display({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-gilda-display",
});

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-barlow",
});

const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gildaDisplay.variable} ${barlow.variable} ${barlowCondensed.variable} antialiased`}
      >
        <RoomProvider>
          <Header />
          {children}
          <Footer />
        </RoomProvider>
      </body>
    </html>
  );
}
